export const ROUTES = {
    ROOT: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    VERIFY_OTP: '/verify-otp',
    DASHBOARD: {
        ROOT: '/dashboard',
        PRODUCTS: 'products',
        PRODUCTS_CREATE: 'products/create',
        PRODUCTS_EDIT: 'products/edit/:id',
        SKUS: 'skus',
        SKUS_CREATE: 'skus/create',
        SKUS_EDIT: 'skus/edit/:id',
        ORDERS: 'orders',
        ORDERS_DETAILS: 'orders/:id',
        REVIEWS: 'reviews',
        RETURNS: 'returns',
        RETURNS_DETAILS: 'returns/:id',
        COUPONS: 'coupons',
        COUPONS_CREATE: 'coupons/create',
        COUPONS_EDIT: 'coupons/edit/:id',

        USERS: 'users',
        USERS_CREATE: 'users/create',
        USERS_EDIT: 'users/edit/:id',

        WHATSAPP_DASHBOARD: 'whatsapp/dashboard',
        WHATSAPP_ACCOUNTS: 'whatsapp/accounts',
        WHATSAPP_ACCOUNTS_DETAILS: 'whatsapp/accounts/edit/:id',
        WHATSAPP_QUEUE: 'whatsapp/queue',
        WHATSAPP_CONTACTS: 'whatsapp/contacts',
        WHATSAPP_RISK: 'whatsapp/risk',
        WHATSAPP_SYSTEM: 'whatsapp/system',
        LOTS: 'lots',
        LOTS_CREATE: 'lots/create',
        LOTS_EDIT: 'lots/edit/:id',
        CATEGORIES: 'categories',
        CATEGORIES_CREATE: 'categories/create',
        CATEGORIES_EDIT: 'categories/edit/:id',
        ATTRIBUTES: 'attributes',
        ATTRIBUTES_CREATE: 'attributes/create',
        ATTRIBUTES_EDIT: 'attributes/edit/:id',
        FILE_MANAGER: 'file-manager',
        STOCK_LEDGER: 'stock-ledger',
        WALLET_DASHBOARD: 'wallet',
        WALLET_RULES: 'wallet/rules',
        WALLET_RULES_CREATE: 'wallet/rules/create',
        WALLET_RULES_EDIT: 'wallet/rules/edit/:id',
        WALLET_TRANSACTIONS: 'wallet/transactions',
        
        // Logistics
        SHIPMENTS: 'shipments',
        SHIPMENT_DETAILS: 'shipments/:id',
        RTO_DASHBOARD: 'rto-dashboard',
        COURIER_CONFIG: 'courier-config',
        WAREHOUSES: 'warehouses',
        WAREHOUSES_CREATE: 'warehouses/new',
        WAREHOUSES_EDIT: 'warehouses/:id',
        NDR_DASHBOARD: 'ndr-dashboard',
        ETA_TEST: 'eta-test',
        CRON_HUB: 'cron-hub',
        THEME_SETTINGS: 'settings/theme',
        CUSTOMER_APP_SETTINGS: 'settings/customer-app',

        // Intelligence Section
        ANALYTICS_SALES: 'intelligence/sales',
        ANALYTICS_PRODUCTS: 'intelligence/products',
        ANALYTICS_CUSTOMERS: 'intelligence/customers',
        ANALYTICS_FINANCIAL: 'intelligence/financial',
        ANALYTICS_LOTS: 'intelligence/lots',
        ANALYTICS_LOGISTICS: 'intelligence/logistics',
        ANALYTICS_COURIERS: 'intelligence/couriers',

        // Payment Management
        PAYMENT_GATEWAYS: 'payment-gateways',
        PAYMENT_GATEWAY_CREATE: 'payment-gateways/new',
        PAYMENT_GATEWAY_EDIT: 'payment-gateways/:name',
        WEBHOOK_LOGS: 'webhook-logs',

        // Marketing & Communication
        NOTIFICATIONS: 'notifications',
        NOTIFICATIONS_CREATE: 'notifications/create',
        NOTIFICATIONS_EDIT: 'notifications/edit/:id',
        BANNERS: 'banners',
        BANNERS_CREATE: 'banners/create',
        BANNERS_EDIT: 'banners/edit/:id',
        FLASH_DEALS: 'flash-deals',
        FLASH_DEALS_CREATE: 'flash-deals/create',
        FLASH_DEALS_EDIT: 'flash-deals/edit/:id',
        SEARCH_QUERIES: 'search-queries',

        // Financial Records
        FINANCIAL_RECORDS: 'financial-records',
        FINANCIAL_RECORDS_CREATE: 'financial-records/create',
        FINANCIAL_RECORDS_EDIT: 'financial-records/edit/:id',
        FINANCIAL_RECORDS_DETAIL: 'financial-records/:id',
        FINANCIAL_ANALYTICS: 'financial-records/analytics',
        REPORTS_TRENDS: 'financial-records/reports/trends',
        REPORTS_CATEGORY: 'financial-records/reports/category',
        REPORTS_LOTS: 'financial-records/reports/lots',
        REPORTS_BANK: 'financial-records/reports/bank',
    },
    PROFILE: '/profile',
    CHANGE_PASSWORD: '/change-password',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
};
