export const ROUTES = {
    ROOT: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    VERIFY_OTP: '/verify-otp',
    DASHBOARD: {
        ROOT: '/dashboard',
        PRODUCTS: 'products',
        PRODUCTS_CREATE: 'products/create',
        PRODUCTS_EDIT: 'products/edit/:id',
        SKUS: 'skus',
        SKUS_CREATE: 'skus/create',
        SKUS_EDIT: 'skus/edit/:id',
        ORDERS: 'orders',
        ORDERS_DETAILS: 'orders/:id',
        REVIEWS: 'reviews',
        RETURNS: 'returns',
        RETURNS_DETAILS: 'returns/:id',
        COUPONS: 'coupons',
        COUPONS_CREATE: 'coupons/create',
        COUPONS_EDIT: 'coupons/edit/:id',

        USERS: 'users',
        USERS_CREATE: 'users/create',
        USERS_EDIT: 'users/edit/:id',
        WHATSAPP: 'whatsapp',
        LOTS: 'lots',
        LOTS_CREATE: 'lots/create',
        LOTS_EDIT: 'lots/edit/:id',
        CATEGORIES: 'categories',
        CATEGORIES_CREATE: 'categories/create',
        CATEGORIES_EDIT: 'categories/edit/:id',
        ATTRIBUTES: 'attributes',
        ATTRIBUTES_CREATE: 'attributes/create',
        ATTRIBUTES_EDIT: 'attributes/edit/:id',
        FILE_MANAGER: 'file-manager',
        INVENTORY_AUDIT: 'inventory-audit',
        LOYALTY: 'loyalty',
        
        // Logistics
        SHIPMENTS: 'shipments',
        SHIPMENT_DETAILS: 'shipments/:id',
        RTO_DASHBOARD: 'rto-dashboard',
        COURIER_CONFIG: 'courier-config',
        WAREHOUSES: 'warehouses',
        WAREHOUSES_CREATE: 'warehouses/new',
        WAREHOUSES_EDIT: 'warehouses/:id',
        NDR_DASHBOARD: 'ndr-dashboard',
        ETA_TEST: 'eta-test',

        // Intelligence Section
        ANALYTICS_SALES: 'intelligence/sales',
        ANALYTICS_PRODUCTS: 'intelligence/products',
        ANALYTICS_CUSTOMERS: 'intelligence/customers',
        ANALYTICS_FINANCIAL: 'intelligence/financial',
        ANALYTICS_LOTS: 'intelligence/lots',
        ANALYTICS_LOGISTICS: 'intelligence/logistics',
        ANALYTICS_COURIERS: 'intelligence/couriers',
    },
    PROFILE: '/profile',
    CHANGE_PASSWORD: '/change-password',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
};
