export const ROUTES = {
    ROOT: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    VERIFY_OTP: '/verify-otp',
    DASHBOARD: {
        ROOT: '/dashboard',
        PRODUCTS: 'products',
        ORDERS: 'orders',
        USERS: 'users',
        USERS_CREATE: 'users/create',
        USERS_EDIT: 'users/edit/:id',
        WHATSAPP: 'whatsapp',
        LOTS: 'lots',
        LOTS_CREATE: 'lots/create',
        LOTS_EDIT: 'lots/edit/:id',
        CATEGORIES: 'categories',
        CATEGORIES_CREATE: 'categories/create',
        CATEGORIES_EDIT: 'categories/edit/:id',
    },
    PROFILE: '/profile',
    CHANGE_PASSWORD: '/change-password',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
};
