export const ROUTES = {
    ROOT: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    VERIFY_OTP: '/verify-otp',
    PRODUCTS: {
        ROOT: '/products',
        DETAILS: '/products/:id',
    },
    CART: '/cart',
    ORDERS: '/orders',
    ORDER_SUCCESS: '/order/success/:orderId',
    PROFILE: '/profile',
    ADDRESSES: '/addresses',
    CHECKOUT: '/checkout',
    WISHLIST: '/wishlist',
    CHANGE_PASSWORD: '/change-password',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
};
