export enum ATTRIBUTE_VALUE_TYPE {
  TEXT = 'TEXT',
  NUMBER = 'NUMBER',
  BOOLEAN = 'BOOLEAN',
  SELECT = 'SELECT',
  MULTI_SELECT = 'MULTI_SELECT',
  COLOR = 'COLOR',
  DATE = 'DATE',
  RANGE = 'RANGE',
}

export enum ATTRIBUTE_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum ATTRIBUTE_INPUT_TYPE {
  TEXT_INPUT = 'TEXT_INPUT',
  NUMBER_INPUT = 'NUMBER_INPUT',
  DROPDOWN = 'DROPDOWN',
  CHECKBOX = 'CHECKBOX',
  RADIO = 'RADIO',
  COLOR_PICKER = 'COLOR_PICKER',
  DATE_PICKER = 'DATE_PICKER',
  RANGE_SLIDER = 'RANGE_SLIDER',
}
