export const SIXTY = 60 as const;
export const ONE_HUNDRED = 100 as const;
export const ONE_THOUSAND = 1000 as const;

export enum USER_TYPE {
  MASTER_ADMIN = 'MASTER_ADMIN',
  ADMIN = 'ADMIN',
  CUSTOMER = 'CUSTOMER',
  SUPPLIER = 'SUPPLIER',
}

export enum GENDER {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
  DO_NOT_TELL = 'DO_NOT_TELL',
  NONE = 'NONE',
}

export enum SIGN_UP_TYPE {
  APP = 'APP',
  GOOGLE = 'GOOGLE',
  APPLE = 'APPLE',
  META = 'META',
}

export enum OTP_TYPE {
  EMAIL = 'EMAIL',
  MOBILE = 'MOBILE',
  ACCOUNT_CREATE = 'ACCOUNT_CREATE',
  FORGET_PASSWORD = 'FORGET_PASSWORD',
}

export enum AUTH_ACTION_TYPE {
  SIGN_IN = 'SIGN_IN',
  SIGN_OUT = 'SIGN_OUT',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
}

export enum TOKEN_TYPE {
  ACCESS_TOKEN = 'ACCESS_TOKEN',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  OTP_TOKEN = 'OTP_TOKEN',
  FORGET_PASSWORD_TOKEN = 'FORGET_PASSWORD_TOKEN',
}

export enum USER_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}


export enum COMMON_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum WHATSAPP_SESSION_STATUS {
  DISCONNECTED = 'DISCONNECTED',
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  QR_READY = 'QR_READY',
}

export enum LOT_TYPE {
  SUPPLIER = 'SUPPLIER',
  SELF_MANUFACTURE = 'SELF_MANUFACTURE',
}

export enum LOT_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  COMPLETED = 'COMPLETED',
}

export enum CATEGORY_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum ADJUST_QUANTITY_TYPE {
  DAMAGE = 'DAMAGE',
  LOST = 'LOST',
  CORRECTION = 'CORRECTION',
  USED = 'USED',
  OTHER = 'OTHER',
  RETURN = 'RETURN',
}

export enum FILE_TYPE {
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  DOCUMENT = 'DOCUMENT',
  AUDIO = 'AUDIO',
  OTHER = 'OTHER',
}

export enum CLOUD_TYPE {
  AWS_S3 = 'AWS_S3',
  CLOUDINARY = 'CLOUDINARY',
}

export enum FILE_STORAGE_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DELETED = 'DELETED',
}
