export enum NDR_REASON {
  CUSTOMER_UNAVAILABLE = 'CUSTOMER_UNAVAILABLE',
  ADDRESS_INCOMPLETE = 'ADDRESS_INCOMPLETE',
  ADDRESS_INCORRECT = 'ADDRESS_INCORRECT',
  CUSTOMER_REFUSED = 'CUSTOMER_REFUSED',
  CASH_NOT_AVAILABLE = 'CASH_NOT_AVAILABLE',
  CUSTOMER_RESCHEDULED = 'CUSTOMER_RESCHEDULED',
  PREMISES_CLOSED = 'PREMISES_CLOSED',
  OTHER = 'OTHER'
}

export enum NDR_STATUS {
  PENDING = 'PENDING',
  CUSTOMER_RESPONDED = 'CUSTOMER_RESPONDED',
  RESCHEDULED = 'RESCHEDULED',
  ADDRESS_UPDATED = 'ADDRESS_UPDATED',
  RTO_INITIATED = 'RTO_INITIATED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED'
}

export enum NDR_CUSTOMER_ACTION {
  RESCHEDULE = 'RESCHEDULE',
  CHANGE_ADDRESS = 'CHANGE_ADDRESS',
  CANCEL_ORDER = 'CANCEL_ORDER',
  PROCEED_WITH_DELIVERY = 'PROCEED_WITH_DELIVERY'
}

export const NDR_MESSAGES = {
  SUCCESS: {
    CREATED: 'NDR created successfully',
    UPDATED: 'NDR updated successfully',
    RESOLVED: 'NDR resolved successfully'
  },
  ERROR: {
    NOT_FOUND: 'NDR not found',
    ALREADY_RESOLVED: 'NDR already resolved',
    INVALID_ACTION: 'Invalid customer action'
  }
};
