export enum ATTRIBUTE_TYPE {
  TEXT = 'TEXT',
  NUMBER = 'NUMBER',
  SELECT = 'SELECT',
  MULTISELECT = 'MULTISELECT',
}

export enum PRODUCT_STATUS {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum SOURCE_TYPE {
  SELF_MANUFACTURE = 'SELF_MANUFACTURE',
  SUPPLIER = 'SUPPLIER',
}

export enum STOCK_MOVEMENT_TYPE {
  PURCHASE = 'PURCHASE',
  SALE = 'SALE',
  ADJUSTMENT = 'ADJUSTMENT',
  RETURN = 'RETURN',
  DAMAGE = 'DAMAGE',
  QUALITY_REJECTION = 'QUALITY_REJECTION',
}

export enum DISCOUNT_TYPE {
  PERCENTAGE = 'PERCENTAGE',
  FIXED_AMOUNT = 'FIXED_AMOUNT',
  BOGO = 'BOGO', // Buy One Get One
  FREE_SHIPPING = 'FREE_SHIPPING',
}

export enum COUPON_APPLICABILITY {
  ALL = 'ALL',
  CATEGORY = 'CATEGORY',
  PRODUCT = 'PRODUCT',
  CART_VALUE = 'CART_VALUE',
  USER_SEGMENT = 'USER_SEGMENT',
}

export enum PAYMENT_METHOD {
  COD = 'COD',
  PREPAID = 'PREPAID',
}
